insert into public.question_sections (code, title, description, sort_order)
values
  ('company_basics', 'Company Basics', 'VSME B1 preparation basis plus supplier identity, reporting boundary, and contact ownership.', 10),
  ('employees', 'Employees', 'VSME B8 and B10 workforce characteristics, representation, training, and workforce policies.', 20),
  ('energy', 'Energy', 'VSME B3 energy consumption, sources, greenhouse gas indicators, and reduction initiatives.', 30),
  ('fuel', 'Fuel', 'Transport and fleet energy data that supports practical supplier passport review.', 40),
  ('waste', 'Waste', 'VSME B7 resource use, circular economy, waste streams, and contractor evidence.', 50),
  ('environmental_policies', 'Environmental Policies', 'VSME B2, B4, B5, and B6 environmental practices, impacts, water, and initiatives.', 60),
  ('health_safety', 'Health & Safety', 'VSME B9 health and safety policies, incidents, training, and risk controls.', 70),
  ('certifications', 'Certifications', 'Supplier passport evidence readiness for management-system, ESG, and industry certificates.', 80),
  ('governance', 'Governance', 'VSME B11 corruption and bribery indicators plus supplier governance and compliance basics.', 90),
  ('supplier_information', 'Supplier Information', 'Buyer-readiness fields for supplier, subcontractor, due-diligence, and evidence requests.', 100)
on conflict (code) do update
set
  title = excluded.title,
  description = excluded.description,
  sort_order = excluded.sort_order;

with section_lookup as (
  select code, id from public.question_sections
)
insert into public.question_items (section_id, code, title, help_text, answer_type, unit, options, evidence_required, questionnaire_level, sort_order)
select section_lookup.id, item.code, item.title, item.help_text, item.answer_type, item.unit, item.options, item.evidence_required, item.questionnaire_level, item.sort_order
from section_lookup
join (
  values
    ('company_basics', 'company_reporting_year', 'Reporting year', 'State the reporting year covered by this Supplier Passport profile.', 'number', null, '[]'::jsonb, false, 'basic', 10),
    ('company_basics', 'company_period_start', 'Reporting period start date', 'Use the first day of the period covered by your answers.', 'date', null, '[]'::jsonb, false, 'basic', 20),
    ('company_basics', 'company_period_end', 'Reporting period end date', 'Use the last day of the period covered by your answers.', 'date', null, '[]'::jsonb, false, 'basic', 30),
    ('company_basics', 'company_legal_name', 'Company legal name', 'Use the official registered legal name.', 'text', null, '[]'::jsonb, false, 'basic', 40),
    ('company_basics', 'company_registration_number', 'Registration, VAT, or company number', 'Provide the primary registration identifier buyers use to verify your company.', 'text', null, '[]'::jsonb, false, 'basic', 50),
    ('company_basics', 'company_country', 'Country', 'Country of headquarters or main registration.', 'text', null, '[]'::jsonb, false, 'basic', 60),
    ('company_basics', 'company_city', 'City / headquarters location', 'City of headquarters or main operating office.', 'text', null, '[]'::jsonb, false, 'basic', 70),
    ('company_basics', 'company_main_activity', 'Main business activity / industry', 'Describe your main activity, NACE code, or sector.', 'text', null, '[]'::jsonb, false, 'basic', 80),
    ('company_basics', 'company_sites_count', 'Number of operating sites or locations', 'Include production, warehouse, office, and service locations if relevant.', 'number', null, '[]'::jsonb, false, 'basic', 90),
    ('company_basics', 'company_reporting_boundary', 'Reporting boundary', 'State whether answers cover this company only or a consolidated group.', 'select', null, '["Company only","Consolidated group","Site-specific","Unknown"]'::jsonb, false, 'basic', 100),
    ('company_basics', 'company_reporting_module', 'Chosen reporting module', 'Select the intended VSME-aligned reporting depth for this profile.', 'select', null, '["Basic","Basic + Comprehensive","Buyer-specific only","Unknown"]'::jsonb, false, 'basic', 110),
    ('company_basics', 'company_sustainability_contact', 'Contact person for sustainability or supplier requests', 'Name or role of the person responsible for buyer sustainability requests.', 'text', null, '[]'::jsonb, false, 'basic', 120),
    ('employees', 'employees_total_headcount', 'Total number of employees / headcount', 'Report headcount at year end or average headcount, using one method consistently.', 'number', null, '[]'::jsonb, false, 'basic', 10),
    ('employees', 'employees_full_time', 'Full-time employees', 'Number of full-time employees in the reporting period.', 'number', null, '[]'::jsonb, false, 'basic', 20),
    ('employees', 'employees_part_time', 'Part-time employees', 'Number of part-time employees in the reporting period.', 'number', null, '[]'::jsonb, false, 'basic', 30),
    ('employees', 'employees_temporary', 'Temporary or seasonal workers, if applicable', 'Include temporary, agency, or seasonal workers where tracked.', 'number', null, '[]'::jsonb, false, 'basic', 40),
    ('employees', 'employees_gender_split_available', 'Is gender split data available?', 'Answer yes if you can provide workforce split by gender for the reporting year.', 'boolean', null, '[]'::jsonb, false, 'basic', 50),
    ('employees', 'employees_turnover_rate', 'Employee turnover rate, if available', 'Provide annual turnover rate or leave blank if not tracked.', 'number', '%', '[]'::jsonb, false, 'basic', 60),
    ('employees', 'employees_training_provided', 'Was workforce training provided during the reporting year?', 'Include safety, compliance, skills, sustainability, or role-specific training.', 'boolean', null, '[]'::jsonb, false, 'basic', 70),
    ('employees', 'employees_collective_bargaining', 'Does collective bargaining apply?', 'State whether employees are covered by collective bargaining or similar representation.', 'select', null, '["Yes","No","Partially","Unknown"]'::jsonb, false, 'full', 80),
    ('employees', 'employees_equal_pay_tracking', 'Does the company track remuneration or equal pay indicators?', 'Answer based on whether these indicators are formally tracked.', 'boolean', null, '[]'::jsonb, false, 'full', 90),
    ('employees', 'employees_workforce_policies', 'Are workforce policies documented?', 'Include employee handbook, HR policies, anti-harassment, working time, or similar policies.', 'boolean', null, '[]'::jsonb, true, 'full', 100),
    ('energy', 'energy_electricity_consumption', 'Electricity consumption', 'Purchased or generated electricity consumed during the reporting period.', 'number', 'kWh', '[]'::jsonb, true, 'basic', 5),
    ('energy', 'energy_natural_gas_consumption', 'Natural gas consumption', 'Natural gas consumed during the reporting period, if applicable.', 'number', 'kWh', '[]'::jsonb, true, 'basic', 8),
    ('energy', 'energy_district_heating_cooling', 'District heating or cooling consumption', 'Report district heating/cooling consumption if applicable.', 'number', 'kWh', '[]'::jsonb, false, 'basic', 9),
    ('energy', 'energy_total_consumption', 'Total energy consumption', 'Include electricity, fuel, heating, cooling, and other energy sources.', 'number', 'kWh', '[]'::jsonb, true, 'basic', 10),
    ('energy', 'energy_consumption_intensity', 'Energy consumption intensity', 'Report energy consumption per unit of revenue, output, or employee.', 'number', 'kWh / employee', '[]'::jsonb, false, 'basic', 20),
    ('energy', 'energy_primary_source', 'Primary source of purchased energy', 'Select the main source of purchased energy.', 'select', null, '["Grid electricity","Natural gas","District heating","Renewable electricity","Other","Unknown"]'::jsonb, false, 'basic', 30),
    ('energy', 'energy_onsite_renewable', 'On-site renewable energy used', 'Consider solar, wind, biomass, geothermal, or other sources.', 'boolean', null, '[]'::jsonb, false, 'basic', 40),
    ('energy', 'energy_renewable_percentage', 'Renewable energy share', 'Enter 0 if renewable energy is not used or not tracked.', 'number', '%', '[]'::jsonb, true, 'basic', 50),
    ('energy', 'energy_scope1_emissions', 'Scope 1 GHG emissions, if calculated', 'Direct greenhouse gas emissions from owned or controlled sources.', 'number', 'tCO2e', '[]'::jsonb, false, 'full', 55),
    ('energy', 'energy_scope2_emissions', 'Scope 2 GHG emissions, if calculated', 'Indirect emissions from purchased electricity, heating, or cooling.', 'number', 'tCO2e', '[]'::jsonb, false, 'full', 58),
    ('energy', 'energy_ghg_method', 'GHG calculation method or tool used', 'Name the calculator, method, emission factor source, or state unknown.', 'text', null, '[]'::jsonb, false, 'full', 59),
    ('energy', 'energy_last_audit', 'Last energy audit or review date', 'Provide the date of your most recent energy audit or assessment.', 'date', null, '[]'::jsonb, true, 'full', 60),
    ('energy', 'energy_efficiency_measures', 'Energy efficiency measures implemented', 'Select all measures already implemented.', 'multi_select', null, '["LED lighting","Efficient equipment","Insulation improvement","Energy monitoring","Process optimization","Other"]'::jsonb, false, 'full', 70),
    ('energy', 'energy_reduction_initiatives', 'Energy or GHG reduction initiatives', 'Summarize active or planned initiatives to reduce energy use or emissions.', 'textarea', null, '[]'::jsonb, false, 'basic', 75),
    ('energy', 'energy_additional_notes', 'Additional energy notes or context', 'Add relevant information about energy use, boundaries, estimates, or initiatives.', 'textarea', null, '[]'::jsonb, false, 'full', 80),
    ('fuel', 'fuel_company_vehicles_count', 'Company vehicles count', 'Number of owned or controlled vehicles used in operations.', 'number', null, '[]'::jsonb, false, 'basic', 10),
    ('fuel', 'fuel_diesel_consumption', 'Diesel consumption', 'Diesel used by company vehicles or equipment.', 'number', 'L', '[]'::jsonb, true, 'basic', 20),
    ('fuel', 'fuel_petrol_consumption', 'Petrol / gasoline consumption', 'Petrol or gasoline used by company vehicles or equipment.', 'number', 'L', '[]'::jsonb, true, 'basic', 30),
    ('fuel', 'fuel_lpg_cng_consumption', 'LPG / CNG consumption, if applicable', 'Report LPG, CNG, or similar alternative fuel consumption.', 'number', 'kg or L', '[]'::jsonb, false, 'full', 40),
    ('fuel', 'fuel_ev_electricity_use', 'Electric vehicle electricity use, if applicable', 'Electricity used for owned or controlled electric vehicles.', 'number', 'kWh', '[]'::jsonb, false, 'full', 50),
    ('fuel', 'fuel_business_travel_tracking', 'Is business travel tracked?', 'Answer yes if flights, rail, hotels, or mileage are tracked.', 'boolean', null, '[]'::jsonb, false, 'full', 60),
    ('fuel', 'fuel_logistics_subcontractor_tracking', 'Are logistics or transport subcontractor data tracked?', 'Answer yes if carrier fuel, activity, or emissions data is requested or recorded.', 'boolean', null, '[]'::jsonb, false, 'full', 70),
    ('fuel', 'fuel_data_source', 'Fuel data source', 'Select the primary source used for fuel data.', 'select', null, '["Invoices","Fleet cards","Meter readings","Estimates","Subcontractor reports","Unknown"]'::jsonb, false, 'basic', 80),
    ('waste', 'waste_total_generated', 'Total waste generated', 'Total waste generated during the reporting period.', 'number', 'kg', '[]'::jsonb, true, 'basic', 10),
    ('waste', 'waste_hazardous_generated', 'Hazardous waste generated', 'Report hazardous waste where applicable.', 'number', 'kg', '[]'::jsonb, true, 'basic', 20),
    ('waste', 'waste_non_hazardous_generated', 'Non-hazardous waste generated', 'Report non-hazardous waste where applicable.', 'number', 'kg', '[]'::jsonb, false, 'basic', 30),
    ('waste', 'waste_recycled_recovered', 'Waste recycled or recovered', 'Waste recycled, reused, recovered, or sent to energy recovery.', 'number', 'kg', '[]'::jsonb, false, 'basic', 40),
    ('waste', 'waste_disposed', 'Waste disposed', 'Waste sent to landfill, incineration without recovery, or other disposal.', 'number', 'kg', '[]'::jsonb, false, 'basic', 50),
    ('waste', 'waste_main_streams', 'Main waste streams', 'List the main waste types, such as packaging, metal, plastics, paper, oils, or chemicals.', 'textarea', null, '[]'::jsonb, false, 'basic', 60),
    ('waste', 'waste_packaging_applicable', 'Is packaging waste applicable?', 'Answer yes if packaging waste is material to your operations or buyer requests.', 'boolean', null, '[]'::jsonb, false, 'basic', 70),
    ('waste', 'waste_contractor_documentation', 'Is waste contractor documentation available?', 'Examples include waste transfer notes, manifests, invoices, or annual summaries.', 'boolean', null, '[]'::jsonb, true, 'basic', 80),
    ('waste', 'waste_circular_initiatives', 'Circular economy or reuse initiatives', 'Describe reuse, repair, reduction, recycled input, or take-back initiatives.', 'textarea', null, '[]'::jsonb, false, 'full', 90),
    ('environmental_policies', 'env_policy_exists', 'Environmental policy exists', 'Answer yes if an environmental policy, procedure, or management commitment is documented.', 'boolean', null, '[]'::jsonb, true, 'basic', 10),
    ('environmental_policies', 'env_climate_energy_targets', 'Climate or energy reduction targets exist', 'Answer yes if targets are documented, even if internal or early-stage.', 'boolean', null, '[]'::jsonb, false, 'basic', 20),
    ('environmental_policies', 'env_pollution_relevant', 'Pollution to air, water, or soil is relevant', 'Answer based on permits, operations, chemicals, emissions, wastewater, or buyer concerns.', 'select', null, '["Yes","No","Unknown"]'::jsonb, false, 'basic', 30),
    ('environmental_policies', 'env_pollution_permits_monitoring', 'Pollution permits or monitoring are applicable', 'Answer yes if permits, inspections, monitoring, or regulatory reports apply.', 'boolean', null, '[]'::jsonb, true, 'full', 40),
    ('environmental_policies', 'env_water_tracked', 'Water withdrawal or consumption is tracked', 'Answer yes if water use is measured through invoices, meters, or estimates.', 'boolean', null, '[]'::jsonb, false, 'basic', 50),
    ('environmental_policies', 'env_water_consumption', 'Water consumption amount, if tracked', 'Report annual water consumption where available.', 'number', 'm3', '[]'::jsonb, false, 'basic', 60),
    ('environmental_policies', 'env_biodiversity_sensitive_sites', 'Biodiversity-sensitive sites near operations', 'State whether operations are near protected or biodiversity-sensitive areas.', 'select', null, '["Yes","No","Unknown"]'::jsonb, false, 'full', 70),
    ('environmental_policies', 'env_incidents_reporting_year', 'Environmental incidents during reporting year', 'Report the number of material incidents, spills, or non-compliances.', 'number', null, '[]'::jsonb, false, 'basic', 80),
    ('environmental_policies', 'env_fines_penalties', 'Environmental fines or penalties during reporting year', 'Report fines or penalties related to environmental matters.', 'number', null, '[]'::jsonb, false, 'basic', 90),
    ('environmental_policies', 'env_planned_initiatives', 'Planned environmental initiatives', 'Summarize practical initiatives planned for the next reporting period.', 'textarea', null, '[]'::jsonb, false, 'basic', 100),
    ('health_safety', 'hs_policy_exists', 'Health and safety policy exists', 'Answer yes if a documented health and safety policy or procedure exists.', 'boolean', null, '[]'::jsonb, true, 'basic', 10),
    ('health_safety', 'hs_work_related_injuries', 'Number of work-related injuries', 'Report injuries recorded during the reporting period.', 'number', null, '[]'::jsonb, false, 'basic', 20),
    ('health_safety', 'hs_recordable_accidents', 'Number of recordable accidents', 'Use your internal or local regulatory definition consistently.', 'number', null, '[]'::jsonb, false, 'basic', 30),
    ('health_safety', 'hs_lost_time_injuries', 'Lost-time injuries, if tracked', 'Report lost-time injuries where tracked.', 'number', null, '[]'::jsonb, false, 'basic', 40),
    ('health_safety', 'hs_fatalities', 'Work-related fatalities', 'Report fatalities during the reporting period.', 'number', null, '[]'::jsonb, false, 'basic', 50),
    ('health_safety', 'hs_absence_rate', 'Sick leave or absence rate, if available', 'Provide absence rate if tracked.', 'number', '%', '[]'::jsonb, false, 'full', 60),
    ('health_safety', 'hs_training_provided', 'Safety training provided', 'Answer yes if workers received health and safety training.', 'boolean', null, '[]'::jsonb, true, 'basic', 70),
    ('health_safety', 'hs_risk_assessments_completed', 'Risk assessments completed', 'Answer yes if workplace or role-based risk assessments are completed and maintained.', 'boolean', null, '[]'::jsonb, true, 'basic', 80),
    ('health_safety', 'hs_certifications_inspections', 'Health and safety certifications or inspections, if applicable', 'List ISO 45001, inspections, audits, or other relevant evidence.', 'textarea', null, '[]'::jsonb, false, 'full', 90),
    ('certifications', 'cert_iso_9001', 'ISO 9001 certification', 'State whether the company currently holds ISO 9001 certification.', 'boolean', null, '[]'::jsonb, true, 'basic', 10),
    ('certifications', 'cert_iso_14001', 'ISO 14001 certification', 'State whether the company currently holds ISO 14001 certification.', 'boolean', null, '[]'::jsonb, true, 'basic', 20),
    ('certifications', 'cert_iso_45001', 'ISO 45001 certification', 'State whether the company currently holds ISO 45001 certification.', 'boolean', null, '[]'::jsonb, true, 'basic', 30),
    ('certifications', 'cert_iso_50001', 'ISO 50001 certification', 'State whether the company currently holds ISO 50001 certification.', 'boolean', null, '[]'::jsonb, true, 'full', 40),
    ('certifications', 'cert_esg_rating', 'EcoVadis, CDP, or other ESG rating', 'Name any ESG rating or platform assessment currently available.', 'text', null, '[]'::jsonb, false, 'full', 50),
    ('certifications', 'cert_industry_specific', 'Industry-specific certificates', 'List certificates required by your sector or buyer, if any.', 'textarea', null, '[]'::jsonb, false, 'basic', 60),
    ('certifications', 'cert_expiry_tracked', 'Certificate expiry dates are tracked', 'Answer yes if expiry dates are actively tracked and reviewed.', 'boolean', null, '[]'::jsonb, false, 'basic', 70),
    ('certifications', 'cert_documents_uploaded', 'Certificate documents uploaded', 'Answer yes if key certificates are uploaded in the Evidence Data Room.', 'boolean', null, '[]'::jsonb, true, 'basic', 80),
    ('certifications', 'cert_insurance_compliance_uploaded', 'Insurance or compliance documents uploaded if relevant', 'Answer yes if buyer-requested insurance or compliance documents are uploaded.', 'boolean', null, '[]'::jsonb, false, 'basic', 90),
    ('governance', 'gov_code_of_conduct', 'Code of conduct exists', 'Answer yes if a code of conduct or equivalent ethics policy exists.', 'boolean', null, '[]'::jsonb, true, 'basic', 10),
    ('governance', 'gov_anti_corruption_policy', 'Anti-corruption policy exists', 'Answer yes if anti-bribery or anti-corruption rules are documented.', 'boolean', null, '[]'::jsonb, true, 'basic', 20),
    ('governance', 'gov_whistleblowing_channel', 'Whistleblowing or reporting channel exists', 'Answer yes if employees or stakeholders can report concerns.', 'boolean', null, '[]'::jsonb, false, 'full', 30),
    ('governance', 'gov_corruption_convictions', 'Convictions for corruption or bribery during reporting year', 'Report the number of confirmed convictions during the reporting year.', 'number', null, '[]'::jsonb, false, 'basic', 40),
    ('governance', 'gov_corruption_fines', 'Fines for corruption or bribery during reporting year', 'Report fines or penalties related to corruption or bribery.', 'number', null, '[]'::jsonb, false, 'basic', 50),
    ('governance', 'gov_data_protection_policy', 'Data protection / GDPR policy exists', 'Answer yes if data protection responsibilities and practices are documented.', 'boolean', null, '[]'::jsonb, false, 'basic', 60),
    ('governance', 'gov_sanctions_screening', 'Sanctions or export-control screening is relevant and performed', 'Answer based on customer, sector, and export exposure.', 'select', null, '["Yes","No","Not applicable","Unknown"]'::jsonb, false, 'full', 70),
    ('governance', 'gov_compliance_responsible_person', 'Responsible person for compliance assigned', 'Name or role responsible for compliance topics.', 'text', null, '[]'::jsonb, false, 'basic', 80),
    ('governance', 'gov_audit_readiness', 'Supplier/customer audit readiness', 'Summarize readiness for customer audits, site visits, or compliance checks.', 'textarea', null, '[]'::jsonb, false, 'basic', 90),
    ('supplier_information', 'supplier_main_suppliers_identified', 'Main suppliers identified', 'Answer yes if your main suppliers are listed and maintained.', 'boolean', null, '[]'::jsonb, false, 'basic', 10),
    ('supplier_information', 'supplier_critical_suppliers_identified', 'Critical suppliers identified', 'Answer yes if critical suppliers are identified by risk, spend, or operational dependency.', 'boolean', null, '[]'::jsonb, false, 'basic', 20),
    ('supplier_information', 'supplier_country_risk_tracked', 'Supplier country risk tracked', 'Answer yes if supplier country or region risk is tracked.', 'boolean', null, '[]'::jsonb, false, 'full', 30),
    ('supplier_information', 'supplier_esg_requirements_exist', 'Supplier ESG or code-of-conduct requirements exist', 'Answer yes if suppliers receive sustainability, ethics, or code-of-conduct expectations.', 'boolean', null, '[]'::jsonb, false, 'full', 40),
    ('supplier_information', 'supplier_questionnaires_collected', 'Supplier sustainability questionnaires collected', 'Answer yes if questionnaires are collected from suppliers or subcontractors.', 'boolean', null, '[]'::jsonb, false, 'full', 50),
    ('supplier_information', 'supplier_evidence_collected', 'Supplier certificates or evidence collected', 'Answer yes if certificates, policies, or declarations are collected from suppliers.', 'boolean', null, '[]'::jsonb, false, 'full', 60),
    ('supplier_information', 'supplier_subcontractors_used', 'Subcontractors used', 'State whether subcontractors are used for production, logistics, installation, or services.', 'boolean', null, '[]'::jsonb, false, 'basic', 70),
    ('supplier_information', 'supplier_due_diligence_process', 'Supplier due-diligence process exists', 'Answer yes if suppliers are checked before onboarding or periodically reviewed.', 'boolean', null, '[]'::jsonb, false, 'full', 80),
    ('supplier_information', 'supplier_buyer_requests_tracked', 'Buyer-specific questionnaire requests tracked', 'Answer yes if buyer requests, deadlines, and evidence needs are tracked.', 'boolean', null, '[]'::jsonb, false, 'basic', 90)
) as item(section_code, code, title, help_text, answer_type, unit, options, evidence_required, questionnaire_level, sort_order)
on section_lookup.code = item.section_code
on conflict (code) do update
set section_id = excluded.section_id, title = excluded.title, help_text = excluded.help_text, answer_type = excluded.answer_type, unit = excluded.unit, options = excluded.options, evidence_required = excluded.evidence_required, questionnaire_level = excluded.questionnaire_level, sort_order = excluded.sort_order;
